version: '2'
services:
    missingconcepts:
        build: 
            context: .
            dockerfile: Dockerfile      
        ports:
            - "3000:3000"
        env_file:
            - .env
            